# Generated by Django 4.2.7 on 2024-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
